=== DataONEorg/d1_schemas/nodelist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://dataone.org/service/types/NodeList/0.1"
  version="0.1"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:common="http://dataone.org/service/types/common/0.1"
  targetNamespace="http://dataone.org/service/types/NodeList/0.1"
  elementFormDefault="unqualified" attributeFormDefault="unqualified">
  <!-- A derived string type with at least length 1 and it must contain digits-->
    <xs:import namespace="http://dataone.org/service/types/common/0.1" 
        schemaLocation="https://repository.dataone.org/software/cicore/trunk/schemas/common.xsd" />
  
  <xs:simpleType name="crontabEntryType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([\*\d]{1,2}[\-,]?)+"/>
    </xs:restriction>
  </xs:simpleType>

    <xs:complexType name="Node">
      <xs:sequence>
        <xs:element name="identifier" type="common:NodeReference" minOccurs="1" maxOccurs="1">
        <xs:annotation>
        <xs:documentation>A unique identifier for the node.  This may initially 
        be the same as the baseURL, however this value should not change for 
        future implementations of the same node, whereas the baseURL may change 
        in the future.
        </xs:documentation>
        </xs:annotation>
        </xs:element>
        <xs:element name="name" type="common:NonEmptyString" />
        <xs:element name="baseURL" type="xs:anyURI"/>
        <xs:element name="services" type="Services" maxOccurs="1" minOccurs="0"/>
        <xs:element name="synchronization" type="Synchronization"  minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="replicate" use="required" type="xs:boolean"/>
      <xs:attribute name="synchronize" use="required" type="xs:boolean"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>

    <xs:complexType  name="Services">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="service" type="Service" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  <xs:complexType  name="Service">
    <xs:attribute name="api" use="required" type="xs:NCName"/>
    <xs:attribute name="available" use="required" type="xs:boolean"/>
    <xs:attribute name="datechecked" use="required" type="xs:dateTime"/>
    <xs:attribute name="method" use="required" type="xs:NCName"/>
    <xs:attribute name="rest" use="required"  type="xs:string"/>
  </xs:complexType>
  
    <xs:complexType name="Synchronization">
      <xs:sequence>
        <xs:element name="schedule" type="Schedule"/>
        <xs:element name="lastHarvested" type="xs:dateTime"/>
        <xs:element name="lastCompleteHarvest" type="xs:dateTime"/>
      </xs:sequence>
    </xs:complexType>

  
    <xs:complexType name="Schedule">
      <xs:attribute name="hour" use="required" type="crontabEntryType"/>
      <xs:attribute name="mday" use="required" type="crontabEntryType"/>
      <xs:attribute name="min" use="required" type="crontabEntryType"/>
      <xs:attribute name="mon" use="required" type="crontabEntryType"/>
      <xs:attribute name="sec" use="required" type="crontabEntryType"/>
      <xs:attribute name="wday" use="required" type="crontabEntryType"/>
      <xs:attribute name="year" use="required" type="crontabEntryType"/>
    </xs:complexType>


    <xs:complexType name='NodeList'>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="node" type="Node" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>

  <xs:element name='nodeList' type='NodeList'>
  </xs:element>

</xs:schema>

=== DataONEorg/d1_schemas/nodelist_instance_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<d1:nodeList xmlns:d1="http://dataone.org/service/types/NodeList/0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dataone.org/service/types/NodeList/0.1 https://repository.dataone.org/software/cicore/trunk/schemas/nodelist.xsd">
    <!-- This instance document was generated for testing purposes
         It contains no useful information.
    -->
	<node replicate="true" type="NodeReference" synchronize="true">
		<identifier>example_daac_mn_id</identifier>
		<name>example_daac_mn</name>
		<baseURL>http://eg.daacmn.dataone.utk.edu</baseURL>
		<services>
			<service datechecked="2010-05-19T08:12:00.123456" rest="????" api="MN_crud" available="true" method="get"/>
			<service datechecked="2010-06-19T08:34:00.123456" rest="????" api="MN_crud" available="true" method="getSystemMetadata"/>
		</services>
		<synchronization>
			<schedule sec="0" min="10,40" hour="*" mon="*" mday="*" wday="*" year="*"/>	
			<lastHarvested>2010-08-23T11:11:11.123456</lastHarvested>
			<lastCompleteHarvest>2010-08-21T12:12:12.123456</lastCompleteHarvest>
		</synchronization>
	</node>
	<node replicate="true" type="NodeReference" synchronize="true">
		<identifier>example_knb_mn_id</identifier>
		<name>example_knb_mn</name>
		<baseURL>http://knb-mn.ecoinformatics.org</baseURL>
		<services>
			<service datechecked="2010-05-19T03:12:00.123456" rest="????" api="MN_crud" available="true" method="get"/>
			<service datechecked="2010-06-19T03:34:00.123456" rest="????" api="MN_crud" available="true" method="getSystemMetadata"/>
		</services>
		<synchronization >
			<schedule sec="0" min="0,30" hour="*" mon="*" mday="*" wday="*" year="*"/>	
			<lastHarvested>2010-08-22T11:11:11.123456</lastHarvested>
			<lastCompleteHarvest>2010-08-20T12:12:12.123456</lastCompleteHarvest>
		</synchronization>
	</node>
</d1:nodeList>
